export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_RECOMMEND_REQUEST = "PRODUCT_RECOMMEND_REQUEST";
export const PRODUCT_RECOMMEND_SUCCESS = "PRODUCT_RECOMMEND_SUCCESS";
export const PRODUCT_RECOMMEND_FAIL = "PRODUCT_RECOMMEND_FAIL";
export const PRODUCT_RECOMMEND_RESET = "PRODUCT_RECOMMEND_RESET";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const SHOP_DETAILS_FAIL = "SHOP_DETAILS_FAIL";
export const SHOP_DETAILS_REQUEST = "SHOP_DETAILS_REQUEST";
export const SHOP_DETAILS_SUCCESS = "SHOP_DETAILS_SUCCESS";

export const PRODUCT_CREATE_REVIEW_REQUEST = "PRODUCT_CREATE_REVIEW_REQUEST";
export const PRODUCT_CREATE_REVIEW_SUCCESS = "PRODUCT_CREATE_REVIEW_SUCCESS";
export const PRODUCT_CREATE_REVIEW_FAIL = "PRODUCT_CREATE_REVIEW_FAIL";
export const PRODUCT_CREATE_REVIEW_RESET = "PRODUCT_CREATE_REVIEW_RESET";

export const SHOP_CREATE_REVIEW_REQUEST = "SHOP_CREATE_REVIEW_REQUEST";
export const SHOP_CREATE_REVIEW_SUCCESS = "SHOP_CREATE_REVIEW_SUCCESS";
export const SHOP_CREATE_REVIEW_FAIL = "SHOP_CREATE_REVIEW_FAIL";
export const SHOP_CREATE_REVIEW_RESET = "SHOP_CREATE_REVIEW_RESET";
